version: '2'
services:
  golang:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/golang:1.12-debian-10
    command: ["sleep", "infinity"] # To keep the container running
